name: otel-shop

x-default-service: &default-service
  env_file: .env
  depends_on:
    db:
      condition: service_healthy

services:
  db:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 30s
      retries: 5

  rabbitmq:
    image: rabbitmq:4.2-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 30s
      timeout: 30s
      retries: 5

  smtp4dev:
    image: rnwood/smtp4dev:v3
    ports:
      - "8085:80"
      - "2525:25"

  initializer:
    <<: *default-service
    image: denoland/deno:2.5.6
    working_dir: /app
    volumes:
      - ./initializer:/app
    restart: on-failure
    command: sh -c "deno task seed-db"

  storefront:
    <<: *default-service
    build:
      context: ./storefront
    working_dir: /app
    env_file: .env
    ports:
      - "8080:3000"
    volumes:
      - ./storefront:/app
      - node-modules:/app/node_modules

  potion-seller:
    <<: *default-service
    image: cosmtrek/air
    working_dir: /app
    ports:
      - 8081:80
    volumes:
      - ./potion-seller:/app
      - go-cache:/go

  weapon-seller:
    <<: *default-service
    image: denoland/deno:2.5.6
    working_dir: /app
    command: deno task dev
    ports:
      - 8082:80
    volumes:
      - ./weapon-seller:/app
      - deno-cache:/deno-dir

  charm-seller:
    <<: *default-service
    working_dir: /var/www/html
    build:
      context: ./charm-seller
    environment:
      APP_ENV: dev
      APP_CACHE_DIR: /var/cache
    ports:
      - 8083:80
    volumes:
      - ./charm-seller:/var/www/html
      - ./docker/charm-seller/apache/app.conf:/etc/apache2/sites-enabled/000-default.conf

  order-service:
    <<: *default-service
    build:
      context: ./order-service
    working_dir: /app
    ports:
      - 8084:80
    volumes:
      - ./order-service:/app
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  scribe-worker:
    <<: *default-service
    build:
      context: ./scribe-worker
    depends_on:
      rabbitmq:
        condition: service_started
      smtp4dev:
        condition: service_started

volumes:
  go-cache:
  deno-cache:
  db-data:
  rabbitmq-data:
  node-modules:

