name: otel-shop
services:
  db:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql

  initializer:
    image: denoland/deno:2.5.6
    env_file: .env
    working_dir: /app
    volumes:
      - ./initializer:/app
    depends_on:
      - db
    restart: on-failure
    command: sh -c "deno task seed-db"

  rabbitmq:
    image: rabbitmq:4.2-management
    ports:
      - "5672:5672" # for amqp
      - "15672:15672" # for management ui
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  potion-seller:
      image: cosmtrek/air
      working_dir: /app
      env_file: .env
      ports:
          - 8081:80
      volumes:
          - ./potion-seller:/app
          - go-cache:/go
  
  weapon-seller:
      image: denoland/deno:2.5.6
      working_dir: /app
      command: deno task dev
      env_file: .env
      ports:
          - 8082:80
      volumes:
          - ./weapon-seller:/app
          - deno-cache:/deno-dir

  charm-seller:
    working_dir: /var/www/html
    build:
      context: ./charm-seller
    env_file: .env
    environment:
      APP_ENV: dev
      APP_CACHE_DIR: /var/cache
    ports:
      - 8083:80
    volumes:
      - ./charm-seller:/var/www/html
      - ./docker/charm-seller/apache/app.conf:/etc/apache2/sites-enabled/000-default.conf

  order-service:
    image: node:24-alpine
    env_file: .env
    working_dir: /app
    ports:
      - 8084:80
    volumes:
      - ./order-service:/app
      - /app/node_modules
    command: sh -c "npm i -g pnpm && pnpm install && pnpm run start:dev"
    depends_on:
      - rabbitmq

  order-worker:
    build:
      context: ./order-worker
    env_file: .env
    volumes:
      - ./order-worker/src:/app/src
      - ./order-worker/requirements.txt:/app/requirements.txt
    command: sh -c "pip install -r requirements.txt && python -u src/worker.py"
    depends_on:
      - db
      - rabbitmq
      - smtp4dev

  storefront:
    image: node:24-alpine
    working_dir: /app
    command: sh -c "npm i -g pnpm && pnpm install && pnpm run dev"
    env_file: .env
    ports:
      - "8080:3000"
    volumes:
      - ./storefront:/app
      - node-modules:/app/node_modules

  smtp4dev:
    image: rnwood/smtp4dev:v3
    ports:
      - "8085:80" # Web interface
      - "2525:25" # SMTP

volumes:
    go-cache:
    deno-cache:
    db-data:
    rabbitmq-data:
    node-modules:
