import type { Metadata } from "next";
import { Header } from "../components/Header.tsx";
import "./globals.css";

import { CartProvider } from "../context/CartContext.tsx";

export const metadata: Metadata = {
  title: "Maxwell's Magical Emporium",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" type="image/png" href="/favicon.png" />
      </head>
      <body>
        <CartProvider>
          <Header />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
