import type { Metadata } from "next";
import { Header } from "../components/Header.tsx";
import "./globals.css";
import { context, propagation } from "@opentelemetry/api";
import { cookies } from "next/headers";

import { CartProvider } from "../context/CartContext.tsx";
import { UserInitializer } from "../components/UserInitializer.tsx";

export const metadata: Metadata = {
  title: "Otellos Magical Emporium",
  description: "Generated by create next app",
};

async function addUserIdToBaggage() {
  const userId = (await cookies()).get("userId");

  const baseCtx = context.active();
  const currentBaggage = propagation.getBaggage(baseCtx) ??
    propagation.createBaggage();

  return userId
    ? propagation.setBaggage(
      baseCtx,
      currentBaggage.setEntry("user.id", { value: userId.value }),
    )
    : baseCtx;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const ctx = await addUserIdToBaggage();

  return context.with(ctx, () => (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" type="image/png" href="/favicon.png" />
      </head>
      <body>
        <UserInitializer />
        <CartProvider>
          <Header />
          {children}
        </CartProvider>
      </body>
    </html>
  ));
}
